---
title: "The Developmental Effects of Conditioning"
format: docx
---

```{r, include=FALSE}
library(readxl)
library(ggplot2)
library(viridis)

viridis_colors <- viridis(10)
```

**Methods:** [Investigating The Effects of a Conditioned Diet on Fitness and Development at Larval and Adult Stages in an Unmanipulated Experiment:]{.ul}

Here, I tested how being reared on a Conditioned diet can affect fitness and development through embryo to adult life stages.

In this experiment, I used vials containing Protein: Carbohydrate (P ) 1:4 food, as this is a diet where females have been known to prefer to lay their eggs, and where they would choose for their offspring to be reared. This P: C diet was used with two different treatments (Conditioned and Unconditioned) to test the development speed from egg to adult.

Flies were reared and were left long enough to mate, flies were then separated on CO2, males were collected, and females were discarded. Males were first collected to be used as the conditioning treatment, n = 30 1:4vials had n = 10 males added to them each. Concurrently, n = 30 1:4 vials were left alone, to be used as the control/ unconditioned treatment. These vials were left in the 25 °C Controlled Temperature (CT) room.

After 24 hours, males from the conditioning treatment vials were discarded, and n = 10 females were added to both the conditioned and unconditioned vials, this was done so females could lay eggs. A following 24 hours later, females were removed from both the conditioned and unconditioned vials and the eggs they had laid in these vials were used for monitoring development.

[Developmental counts:]{.ul}

After females had been removed from the conditioned and unconditioned vials, both treatments were placed back in the 25 °C CT room, where they were left to develop. A following 8 days (192 hours) later, pupae started to emerge and were first counted. These were counted twice, daily, and were counted by marking on the vials where pupae were, to reduce the risk of double pupae counts. 12 days after eggs were laid in the vials (289 hours) flies started to eclose. Flies were put on CO2, were separated by sex, and were counted and placed in Eppendorf's in the - 20 °C freezer. Pupae counts were stopped after 4 days of flies emerging, and fly counts were stopped 10 days after flies started to emerge, to avoid risk of double counting.

[Body weight of adults:]{.ul}

When development counts and the collection had finished, flies were selected based on peak emergence and had their body weight measured using an A&D Analytical Balance.

[Investigating The Effects of a Conditioned Diet on Fitness and Development at Larval and Adult Stages in a Manipulated Experiment:]{.ul}

Like in the manipulated fitness experiment, flies will first be collected to be male conditioning flies.

The next set of flies was collected; by putting 8 plates across 4 different Dahomey population cages, these were left in the cages for 4 hours and were left to incubate in a pillowcase for 26 hours from the middle point of being in the cage.

n = 63 first instar larvae were picked into n = 15 conditioned vials, and n = 15 unconditioned vials. These were left in the 25 CT room to monitor the development between the vials.

As pupae started to develop, vials were marked twice a day, and the same for flies when they started to develop.

[Results:]{.ul}

When the development of flies from the embryo stage was monitored on Conditioned and Unconditioned no-choice diets after females were allowed to lay wherever. The development speed of flies reared on the unconditioned diets was faster than those in the conditioned. However, results also showed that the number of flies counted on the 1:4 diets, was higher in the conditioned diets over the unconditioned diets, suggesting an effect of developmental speed.

[Unmanipulated:]{.ul}

[Pupae development :]{.ul}

The developmental speed was significantly higher in Unconditioned vials than in Conditioned vials in the development of pupae. There was an interaction effect found between the treatment (conditioned and unconditioned), and the time of emergence (Zero Inflation Poisson: n = 60, LRT = 123.83, P \< 0.0001), so this was kept in the model.

The model was then used to look at the effect of treatment and time of emergence, as well as an interaction effect of treatment and time of emergence on the number of pupae emerging. At the earliest time point in pupae emergence (202 hours), there was found to be a significant difference between pupae emerging in the conditioned vials vs. the unconditioned vials (Zero Inflation Poisson: n = 605, z = 5.337, P \< 0.0001), with a coefficient estimate value of 6.5 more pupae emerging in an unconditioned vial over a conditioned vials at this time point. In conditioned vials, there was found to be a significant difference in pupae emerging, as the time increased (Negative Binomial GLM: n = 605, z = 6.529, P \< 0.0001), with an estimated coefficient of 1 less fly emerging at each time point. In addition to this, there was an interaction effect found between conditioned and time hours, and unconditioned and emergence time (Negative Binomial GLM: n = 605, z = 8.689, P \< 0.0001), with an estimate coefficient value of less than 1 pupae emerging as time goes on in the unconditioned vials, compared to the conditioned vials. This shows that, as time goes on, the emergence of pupae in unconditioned vials decreases, and the emergence of pupae in conditioned vials increases.

{r}
pupae_fitness_2 \<- read_excel("data/fitness_development/pupae_data_2.xlsx")

pupae_boxplot_2 \<- ggplot(pupae_fitness_2, aes(x = time_hours, y = pupae, fill = treatment)) +
geom_boxplot(outliers = FALSE, alpha =.4, position = position_dodge (width = 20)) + #width =10 ) +
geom_point(aes(fill = treatment),
size = 1.5, shape = 21,
position = position_jitterdodge(jitter.width = 6, dodge.width = 20)) +
scale_fill_manual(values = viridis_colors\[c(4,8)\], labels = c("Conditioned", "Unconditioned")) +
scale_x\_continuous(breaks = unique(pupae_fitness_2\$time_hours), labels = unique(pupae_fitness_2\$time_hours)) +
theme_classic() +
theme(legend.position = "top",
legend.justification = "right",
legend.direction = "vertical",
strip.placement = "outside",
strip.background = element_blank(),
strip.text = element_blank()) +
labs(x = "Time (hours) since eggs laid",
y = "Number of pupae emerged",
fill = "Treatment") +
facet_grid(\~time_hours, scales = "free_x")

pupae_boxplot_2
